### ISSUE TITLE
Consolidate react-native MPChart libraries

### ISSUE THREAD

**Issue by mikemonteith** [hongyin163/react-native-chart-android#1]
It seems that there are a few different people working on very similar projects.
Maybe it would be best if we all focused our efforts in once place?

**Comment by mikemonteith** [comment]
see https://github.com/joddiy/react-native-mp-android-chart/issues/1 for discussion

**Comment by cablegunmaster** [comment]
Seems like a good idea actually. I support this as well. eventhough I like competition as well!
