### ISSUE TITLE
Doesn't works with react native 0.25 

### ISSUE THREAD

**Issue by cablegunmaster** [hongyin163/react-native-chart-android#17]
Tried to follow the installation of this plugin but the MainActivity is not the same as described.
Could you test it , and check if its possible to run under v0.25?

app/src/main/java/com/app/MainActivity.java

```
package com.app;

import com.facebook.react.ReactActivity;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import cn.mandata.react_native_mpchart.MPChartPackage;

import java.util.Arrays;
import java.util.List;

public class MainActivity extends ReactActivity {

/**
 * Returns the name of the main component registered from JavaScript.
 * This is used to schedule rendering of the component.
 */
@Override
protected String getMainComponentName() {
    return "App";
}

/**
 * Returns whether dev mode should be enabled.
 * This enables e.g. the dev menu.
 */
@Override
protected boolean getUseDeveloperSupport() {
    return BuildConfig.DEBUG;
}

/**
 * A list of packages used by the app. If the app uses additional views
 * or modules besides the default ones, add more packages here.
 */
@Override
protected List<ReactPackage> getPackages() {
    return Arrays.<ReactPackage>asList(
        new MainReactPackage(),
        new MPChartPackage()
    );
  }
}
```

Update: added the line in getPackages() testing now if it works on v0.25

**Comment by hongyin163** [comment]
It now work on 0.20,I will update to 0.25.

**Comment by cablegunmaster** [comment]
Awesome! :+1: Trying to get this working in my script and wondering how to use the import function.

Example says:

```
  var {
         BarChart,
         CombinedChart
     }=require('../index.android');
```

But in react-native you would more expect something like this:

```
import React, {
    Component,
    View,
    Text
} from 'react-native';
```

How can I import it like this?

**Comment by hongyin163** [comment]
@cablegunmaster yes , web have to do this in 0.25,I will update it in this weekend。

**Comment by hongyin163** [comment]
@cablegunmaster  you can change it and test it  and pull request

**Comment by tuananhdn** [comment]
did it work for 0.25 now? :(. I try to use it with sample data but nothing show.

**Comment by hongyin163** [comment]
@tuananhdn no ,now support 0.20

**Comment by eriksape** [comment]
is still on 0.20?

**Comment by lakeoffaith** [comment]
you can use it edit or copy resouce to you project to make some simple chart work, you will find it work in the lastest version of react native,do it.

**Comment by hongyin163** [comment]
@lakeoffaith thanks

**Comment by jakobinn** [comment]
Yes for the new version of react native you would do:

import {
     BarChart,
     CombinedChart,
     LineChart,
 } from 'react-native-chart-android';

The documentation hasn't been updated.
