### ISSUE TITLE
Application crash after using react-native-chart-android

### ISSUE THREAD

**Issue by JagdishUpadhyay** [hongyin163/react-native-chart-android#31]
I am getting following issue after using react-native-chart-android. My react-native version is 0.29

![screenshot_20160709-170929](https://cloud.githubusercontent.com/assets/11144207/16707802/594cd36e-45f9-11e6-8f84-43ff42e73237.png)

**Comment by JagdishUpadhyay** [comment]
I got the reason for crash. Please release the **Fix react native .25 breaking changes** , so that we can use it.

**Comment by hongyin163** [comment]
@JagdishUpadhyay OK

**Comment by JagdishUpadhyay** [comment]
Thanks, fixed for me. Closing the issue.
