### ISSUE TITLE
Is there any whole sample for how to integrate this into my local android Project?

### ISSUE THREAD

**Issue by raywang8341** [hongyin163/react-native-chart-android#32]
Hi,
I'm a new to react-native world. How to integrate this lib/component(react-native-chart-android) in my react-native android project? 

http://stackoverflow.com/questions/38363710/how-to-integrate-this-lib-component-in-my-react-native-android-project

Could you please provide a whole sample.

Thanks very much.

**Comment by hongyin163** [comment]
http://facebook.github.io/react-native/docs/integration-with-existing-apps.html
