### ISSUE TITLE
How to set CUBIC_BEZIER for line chart

### ISSUE THREAD

**Issue by peter4k** [hongyin163/react-native-chart-android#33]
Hi, I am trying to config the dataset to be CUBIC_BEZIER for a line chart, tried some settings but does not work. Can you give me a simple instruction how to do it?
Thank you!

**Comment by hongyin163** [comment]
you can to  to mpandroidchart wiki to find this api  , then change this project ,thanks!

**Comment by card-b** [comment]
I figured it out. In MPLineChartManager.java, after the line:

`if (config.hasKey("fillAlpha")) dataSet.setFillAlpha((int)(255 * config.getDouble("fillAlpha")));`

add the line:

`if (config.hasKey("bezier")) dataSet.setDrawCubic(config.getBoolean("bezier"));`

then in your JS when you set the data variable you can set a boolean for bezier: 

```
    data['yValues']=[
      {
        data:[],
        label:'My Label',
        config:{
          color:'black',
          drawCircles: false,
          bezier: true //<--- add this to config
        }
      }
    ];
```
