### ISSUE TITLE
Text color in Pie Chart 

### ISSUE THREAD

**Issue by MeirLejz** [hongyin163/react-native-chart-android#35]
Hello,

Thank you for the plug in.

I am using a Pie Chart and I can't figure out how to change the text color of the percentages written inside the Pie.

There are also many properties I did not manage to use : for example i cannot change the radius of the transparent circle. 

Could someone please give me a link to the right list of properties ? 

Here is my Pie Chart :

`
 const data = {
      xValues:['Client','Project','Management','Marketing','Growth','Network'],
      yValues:[{
        data : [35,22,11,18, 7, 7],
        label : '', 
        config:{
          colors: catColors,
          color : 'white',
          fontSize : 35
        },
      }],
    }

  return  (
  <PieChart data = {data} 
          style={progressStyle.pie} 
          holeRadius={51}
          dragDecelerationEnabled={true}
          dragDecelerationFrictionCoef={0.8}
          usePercentValue={true}
          legend={{enable : false}}
          transparentCircleRadius={80}
          description={''}  />)
`

Thank you for your help

**Comment by mlumbroso** [comment]
Hi,

also interested in this, and in addition being able to customize the text displayed, not only its style. Thanks a lot for providing directions.

**Comment by hongyin163** [comment]
@mlumbroso 
you can look up this solution in mpandroidchart project,then add this futrue in this  project

**Comment by kenny221** [comment]
Hi,

I have a problem similar to this and I was wondering if there is an option to not show the percentages and also get rid of the percentage sign? 

Thanks, this library has been extremely helpful!

**Comment by hongyin163** [comment]
sorry i did not understand 'get rid of the percentage sign'
this lib use mpandroidchart project ,so mpchart is really good project^^

**Comment by fabripeco** [comment]
Hi,
I'm wondering about how to hide the default labels in the slice of the pie chart (e.g. 26.5%). The prop drawSliceText={false} doesn't seem to work. 

My jsx is the following:
```
<PieChart
	data={this.getPieData()}
	style={{flex: 1, width: 200, height: 200}}
	legend={{enable: false}}
	doubleTapToZoomEnabled={true}
	maxVisibleValueCount={20}
	description={""}
	drawSliceText={false}
	holeRadius={50}
	centerText={"..."} />
```

EDIT: This point solved by setting drawValues: false in the config of the data object.
```
pieData.xValues = [];
pieData.yValues = [{
data: yValues,
	label: '',
	config: {
	       colors: colors,
		drawValues: false
	}
}];
```
Anyway, documentation seems to be poor in my opinion, even if the project is very well done


I have also notice that the PieChart crashes the app  when I don't set height and width (RN 0.32). Any ideas?

thank you for your help

**Comment by hongyin163** [comment]
@fabripeco  if you have native develop ide ,you can debug this problem ,this lib is form mpandroidchart,so you can look up mpandroidchar wiki for api description,you also can change natvie code in your project and test it
