### ISSUE TITLE
Upgrade to 0.19.0

### ISSUE THREAD

**Issue by Taakn** [hongyin163/react-native-chart-android#4]
Hello,

It looks like your component is not compatible with RN 0.19.0. Would it be possible for you to upgrade it? Thanks so much

**Comment by hongyin163** [comment]
Ok ,I will upgrade to 0.19 发自网易邮箱大师 On 2016-02-13 01:49 , Taakn Wrote: Hello, It looks like your component is not compatible with RN 0.19.0. Would it be possible for you to upgrade it? Thanks so much — Reply to this email directly or view it on GitHub.

**Comment by matc4** [comment]
+1

**Comment by hongyin163** [comment]
@Taakn @matiascba this project has update to 0.20
