### ISSUE TITLE
为什么显示不了负数呢？

### ISSUE THREAD

**Issue by ShunquanWang** [hongyin163/react-native-chart-android#46]

**Comment by ShunquanWang** [comment]
![image](https://cloud.githubusercontent.com/assets/18063209/19586267/16d2af20-9786-11e6-8bbc-0d4e9c4edf68.png) 
![image](https://cloud.githubusercontent.com/assets/18063209/19586532/4e32246c-9788-11e6-81ad-00c74a99f14f.png)
![Uploading image.png…]()

**Comment by hongyin163** [comment]
@kenvies 看看坐标轴的显示范围呢？

**Comment by ShunquanWang** [comment]
找到原因了，非常感谢
