### ISSUE TITLE
How can I set color of the x and y labels?

### ISSUE THREAD

**Issue by sakshityagi** [hongyin163/react-native-chart-android#49]
By defaults they show in black color, but my chart's background is already black and these labels are not visible now. Can you please tell me how can I customize this?

**Comment by sakshityagi** [comment]
@hongyin163 Any updates on this? Thanks.

**Comment by hongyin163** [comment]
You can set xAxis or yAxis propery
like :
 xAxis={{textColor:"#FFFFFF"}}

**Comment by hongyin163** [comment]
if you want to change lengen ,refer to 
![Uploading image.png…]()

**Comment by hongyin163** [comment]
if you want to change legend ,refer to 

![mpcharit0](https://cloud.githubusercontent.com/assets/3040906/19919022/11a9cdce-a10b-11e6-9248-7f8bb934cc3a.png)

**Comment by sakshityagi** [comment]
@hongyin163 Thanks. It helped. :)
