### ISSUE TITLE
No chart data available

### ISSUE THREAD

**Issue by Mokto** [hongyin163/react-native-chart-android#5]
Hi,

Using you exemple provide in BarChart.js, I got two times "No chart data available".

Any idea ?

I'm using React Native 0.19.0.

Thanks !

**Comment by hongyin163** [comment]
I will upgrade to 0.19 and test it 

Thanks!

**Comment by WangMingJue** [comment]
If you use android native view, and annotations ReactProp. Please import the right ReactProp class, import com.facebook.react.uimanager.annotations.ReactProp, rather than import com.facebook.react.uimanager.ReactProp.

com.facebook.react.uimanager.ReactProp is not work on 0.19.0.

**Comment by gtjll** [comment]
I meet the same problem,Would you please update to 0.19?Thank you so much!

**Comment by hongyin163** [comment]
@WangMingJue Thanks!  i will replace it

**Comment by hongyin163** [comment]
This problem is solved,thank you all!
