### ISSUE TITLE
能触摸数据响应事件吗

### ISSUE THREAD

**Issue by jinleli** [hongyin163/react-native-chart-android#50]
您好，请问这个组件能支持触摸事件吗，比如图表上的数据节点是[5,7,3,5,3]，我触摸7能够把点击的X轴和y轴数据当参数传入跳转页面或者其他响应去看具体的内容，不知道有没有这方面的API

**Comment by jinleli** [comment]
我看到MPAndroidChart里面有一个setOnChartValueSelectedListener的API，我应该在这个组件中怎么用这个API呢

**Comment by jinleli** [comment]
找到了在onSelect属性中可以获取触摸事件e.nativeEvent可以取到xIndex和yValue
`onSelect() {
    return function(e) {
            console.log(e.nativeEvent);
        }
    }`

**Comment by hongyin163** [comment]
@jinleli 
you can add it to this project
