### ISSUE TITLE
Is radar chart supported?

### ISSUE THREAD

**Issue by xzyaoi** [hongyin163/react-native-chart-android#54]
I've been trying to insert a radar chart in my project, but i found it seems that this repo did not support it. Is there any way I can diy it or do you have any schedules?

**Comment by hongyin163** [comment]
There is radar chart in mpandroidchart project ,you can refer to MPPieChartManager  ,make a MPRadarChartManager   that extends MPPieRadarChartManager.
You can  go to mpandroidchart wiki to learn how to use radar chart ,how to init and set data.
thanks.

**Comment by xzyaoi** [comment]
Done it as the PR #56

**Comment by xzyaoi** [comment]
Can you upload it to npm? @hongyin163

**Comment by hongyin163** [comment]
ok
