### ISSUE TITLE
can it be dynamically updated?

### ISSUE THREAD

**Issue by leonardgithub** [hongyin163/react-native-chart-android#6]
Hi Hongyin,
    how can I dynamically update the chart? E.g. add data, remove data, and so forth. By the way, the 慢牛 app's source code can be opened and released out? I am so interested in it. thanks

**Comment by carlos-wong** [comment]
It can be update by set the Data as component state value. I have tested.

**Comment by leonardgithub** [comment]
@carlos-wong I did it like you said, but failed. 
// render code:
<LineChart 
                    style={{flex:1}} 
                    data={this.state.lineData}
// js code:
var data = ....
this.setState({lineData: data});
after the above code is executed and I drag the chart, the data are changed correctly. i.e. It will not refresh automatically until I drag the chart

**Comment by hongyin163** [comment]
@leonardgithub You can use android studio to debug it , when you setState , the chart date will be replace with new data , is there something block the chart update ? you can lookup the log to find the reason.

**Comment by leonardgithub** [comment]
@hongyin163 Another question. There is no examples which show how to init line chart with default data or empty data, fetch data from server, and render the line chart with the fetched data. Since I must fetch data from server, and it seems that the fetch can not be synchronous, it is async. Can you provide an example?

**Comment by hongyin163** [comment]
@leonardgithub You can fetch data by ajax,then setState,if you setState ,the chart will update.

**Comment by hongyin163** [comment]
@leonardgithub You can use flux pattern，fetch data in action and update store.

**Comment by leonardgithub** [comment]
@hongyin163 H, hongyin, I show your example of  react-native-chart-android/sample/LineChart.js
, but do you know how to hide the labels and the circles of the data points, I just want to get a smooth curve line chart without any labels. 
thanks

**Comment by hongyin163** [comment]
You can set   xAxis={{enable:false,drawGridLines:false,gridLineWidth:0}}

You can set data in this format,the config part can remove circles 
var avgData={
            xValues:[],
            yValues:[
                {
                    data:[],
                    label:"K",
                    config:{
                        drawCircles:false,
                        color:'#FF0080'
                    }
                }]
}

**Comment by leonardgithub** [comment]
the circles disappear, but the labels of data points not yet, do you know how? By the way, some attributes of your plugin and the MPChart are not the same, and there is just few detailed API docs for the attribute config on your github, can you privide some?

**Comment by hongyin163** [comment]
you can see mpchart's wiki doc https://github.com/PhilJay/MPAndroidChart/wiki/The-Axis

xAxis={{enable:false,drawGridLines:false,gridLineWidth:0}}

setEnable(false)
setDrawGridLines(false)
setGridLineWidth(0)

https://github.com/hongyin163/react-native-chart-android/blob/master/android/src/main/java/cn/mandata/react_native_mpchart/MPBarLineChartManager.java#L168

I convert mpchart api like this,you can see source code to set it.

`    private void setAxisInfo(AxisBase axis,ReadableMap v){
        if(v.hasKey("enable")) axis.setEnabled(v.getBoolean("enable"));
        if(v.hasKey("drawAxisLine")) axis.setDrawAxisLine(v.getBoolean("drawAxisLine"));

```
    if(v.hasKey("drawGridLines")) axis.setDrawGridLines(v.getBoolean("drawGridLines"));
    if(v.hasKey("drawLabels")) axis.setDrawLabels(v.getBoolean("drawLabels"));

    if(v.hasKey("textColor")) axis.setTextColor(Color.parseColor(v.getString("textColor")));
    if(v.hasKey("gridColor")) axis.setGridColor(Color.parseColor(v.getString("gridColor")));

    if(v.hasKey("gridLineWidth")) axis.setGridLineWidth((float)v.getDouble("gridLineWidth"));
    if(v.hasKey("axisLineColor")) axis.setAxisLineColor(Color.parseColor(v.getString("axisLineColor")));
    if(v.hasKey("axisLineWidth")) axis.setAxisLineWidth((float)(v.getDouble("axisLineWidth")));
    if(v.hasKey("gridDashedLine")) {
        ReadableMap gdl=v.getMap("gridDashedLine");
        axis.enableGridDashedLine((float)gdl.getDouble("lineLength"),
                (float)gdl.getDouble("spaceLength"),
                (float)gdl.getDouble("phase"));
    }

}`
```

**Comment by leonardgithub** [comment]
@hongyin163 Thanks, but I mean the labels of yValue points, not the axis's labels. I see the setData method in MPLineChartManager.java, it seems no any properties related to labels of yValue points.

**Comment by hongyin163** [comment]
@leonardgithub you can see yAxis's config?

**Comment by cnjon** [comment]
@leonardgithub 
Do you have any solution of dynamically update the chart ? I have the same problem。
The data are changed but not refresh until I press the chart。
I just init a new project.

```
'use strict';
import React, {
    AppRegistry,
    Component,
    StyleSheet,
    Text,
    View
} from 'react-native';

import {
    BarChart,
    CombinedChart
} from 'react-native-chart-android';

export default class TestChart extends Component {
    constructor(props) {
        super(props);
        this.state = {
            index: 0
        };
    }

    getRandomData() {
        var data={};
        data['xValues']=[];
        data['yValues']=[
            {
                data:[],
                label:'test'+ this.state.index,
                config:{
                    color:'blue'
                }
            }
        ];
        for (var i = 0; i < 500; i++) {
            data.xValues.push(i+'');
            data.yValues[0].data.push(Math.random()*100);
        }
        setTimeout(()=>{
            this.setState({index: this.state.index + 1});
        }, 2000);
        return data;
    }

    render() {
        return (
            <View style={styles.chartContainer}>
                <BarChart
                    style={{flex:1}}
                    data={this.getRandomData()}
                    visibleXRange={[0,30]}
                    maxVisibleValueCount={50}
                    xAxis={{drawGridLines:false,gridLineWidth:1,position:"BOTTOM"}}
                    yAxisRight={{enable:false}}
                    yAxis={{startAtZero:false,drawGridLines:false,position:"INSIDE_CHART"}}
                    drawGridBackground={false}
                    backgroundColor={"WHITE"}
                    description={"测试"}
                    legend={{enable:true,position:'ABOVE_CHART_LEFT',direction:"LEFT_TO_RIGHT"}}
                />
            </View>
        );
    }
}

const styles = StyleSheet.create({
    container:{
        flex:1
    },
    chartContainer:{
        flex:1
    },
    chart:{
        flex:1
    }
});
```

**Comment by leonardgithub** [comment]
@cnjon I have a similar problem as you did. Now my solution is pre-load the chart data, and then send the chart data as props to the component when routing to the component

**Comment by salhk** [comment]
in MPLineChartManager.java

invalidate the view to force update

chart.setBackgroundColor(Color.WHITE);
chart.setData(chartData);
**chart.invalidate();**

**Comment by cnjon** [comment]
@jimmymeego Thanks, it's work fine.

**Comment by leonardgithub** [comment]
Anyone succeeded to try the sample/CandleChart.js? I got the below error:

Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `ZuotStockDetail`.reactConsoleError @ ExceptionsManager.js:76console.error @ YellowBox.js:48warning @ warning.js:45ReactElementValidator.createElement @ ReactElementValidator.js:221render @ zuot-stock-detail.js:249ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext @ ReactCompositeComponent.js:587ReactCompositeComponentMixin._renderValidatedComponent @ ReactCompositeComponent.js:607ReactPerf.measure.wrapper @ ReactPerf.js:66ReactCompositeComponentMixin.mountComponent @ ReactCompositeComponent.js:220ReactPerf.measure.wrapper @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:37ReactCompositeComponentMixin.mountComponent @ ReactCompositeComponent.js:225ReactPerf.measure.wrapper @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:37ReactMultiChild.Mixin.mountChildren @ ReactMultiChild.js:241ReactNativeBaseComponent.Mixin.initializeChildren @ ReactNativeBaseComponent.js:78ReactNativeBaseComponent.Mixin.mountComponent @ ReactNativeBaseComponent.js:215ReactReconciler.mountComponent @ ReactReconciler.js:37ReactCompositeComponentMixin.mountComponent @ ReactCompositeComponent.js:225ReactPerf.measure.wrapper @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:37ReactMultiChild.Mixin.mountChildren @ ReactMultiChild.js:241ReactNativeBaseComponent.Mixin.initializeChildren @ ReactNativeBaseComponent.js:78ReactNativeBaseComponent.Mixin.mountComponent @ ReactNativeBaseComponent.js:215ReactReconciler.mountComponent @ ReactReconciler.js:37ReactCompositeComponentMixin.mountComponent @ ReactCompositeComponent.js:225ReactPerf.measure.wrapper @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:37ReactMultiChild.Mixin._mountChildByNameAtIndex @ ReactMultiChild.js:474ReactMultiChild.Mixin._updateChildren @ ReactMultiChild.js:378ReactMultiChild.Mixin.updateChildren @ ReactMultiChild.js:326ReactNativeBaseComponent.Mixin.receiveComponent @ ReactNativeBaseComponent.js:143ReactReconciler.receiveComponent @ ReactReconciler.js:87ReactCompositeComponentMixin._updateRenderedComponent @ ReactCompositeComponent.js:562ReactCompositeComponentMixin._performComponentUpdate @ ReactCompositeComponent.js:544ReactCompositeComponentMixin.updateComponent @ ReactCompositeComponent.js:473ReactPerf.measure.wrapper @ ReactPerf.js:66ReactCompositeComponentMixin.receiveComponent @ ReactCompositeComponent.js:405ReactReconciler.receiveComponent @ ReactReconciler.js:87ReactChildReconciler.updateChildren @ ReactChildReconciler.js:84ReactMultiChild.Mixin._reconcilerUpdateChildren @ ReactMultiChild.js:216ReactMultiChild.Mixin._updateChildren @ ReactMultiChild.js:351ReactMultiChild.Mixin.updateChildren @ ReactMultiChild.js:326ReactNativeBaseComponent.Mixin.receiveComponent @ ReactNativeBaseComponent.js:143ReactReconciler.receiveComponent @ ReactReconciler.js:87ReactCompositeComponentMixin._updateRenderedComponent @ ReactCompositeComponent.js:562ReactCompositeComponentMixin._performComponentUpdate @ ReactCompositeComponent.js:544ReactCompositeComponentMixin.updateComponent @ ReactCompositeComponent.js:473ReactPerf.measure.wrapper @ ReactPerf.js:66ReactCompositeComponentMixin.receiveComponent @ ReactCompositeComponent.js:405ReactReconciler.receiveComponent @ ReactReconciler.js:87ReactCompositeComponentMixin._updateRenderedComponent @ ReactCompositeComponent.js:562ReactCompositeComponentMixin._performComponentUpdate @ ReactCompositeComponent.js:544ReactCompositeComponentMixin.updateComponent @ ReactCompositeComponent.js:473ReactPerf.measure.wrapper @ ReactPerf.js:66ReactCompositeComponentMixin.performUpdateIfNecessary @ ReactCompositeComponent.js:421ReactReconciler.performUpdateIfNecessary @ ReactReconciler.js:102runBatchedUpdates @ ReactUpdates.js:129Mixin.perform @ Transaction.js:136Mixin.perform @ Transaction.js:136assign.perform @ ReactUpdates.js:86flushBatchedUpdates @ ReactUpdates.js:147ReactPerf.measure.wrapper @ ReactPerf.js:66Mixin.closeAll @ Transaction.js:202Mixin.perform @ Transaction.js:149ReactDefaultBatchingStrategy.batchedUpdates @ ReactDefaultBatchingStrategy.js:62enqueueUpdate @ ReactUpdates.js:176enqueueUpdate @ ReactUpdateQueue.js:24ReactUpdateQueue.enqueueSetState @ ReactUpdateQueue.js:190ReactComponent.setState @ ReactComponent.js:65React.createClass.push @ Navigator.js:913before.obj.(anonymous function) @ aspect.js:32after.obj.(anonymous function) @ aspect.js:43onForward @ index.js:134babelHelpers.createClass.value.goForward @ index.js:223toDetail @ zuot-view.js:41exports.ZuotView.babelHelpers.createClass.value._reactNative2.default.createElement._reactNative2.default.createElement.renderRow._reactNative2.default.createElement._reactNative2.default.createElement.onPress @ zuot-view.js:287React.createClass.touchableHandlePress @ TouchableHighlight.js:168TouchableMixin._performSideEffectsForTransition @ Touchable.js:691TouchableMixin._receiveSignal @ Touchable.js:607TouchableMixin.touchableHandleResponderRelease @ Touchable.js:395invokeGuardedCallback @ ReactErrorUtils.js:27executeDispatch @ EventPluginUtils.js:79executeDispatchesInOrder @ EventPluginUtils.js:102executeDispatchesAndRelease @ EventPluginHub.js:43executeDispatchesAndReleaseTopLevel @ EventPluginHub.js:54forEachAccumulated @ forEachAccumulated.js:23EventPluginHub.processEventQueue @ EventPluginHub.js:259runEventQueueInBatch @ ReactEventEmitterMixin.js:18ReactEventEmitterMixin.handleTopLevel @ ReactEventEmitterMixin.js:34merge._receiveRootNodeIDEvent @ ReactNativeEventEmitter.js:120merge.receiveTouches @ ReactNativeEventEmitter.js:205__callFunction @ MessageQueue.js:184(anonymous function) @ MessageQueue.js:88guard @ MessageQueue.js:42callFunctionReturnFlushedQueue @ MessageQueue.js:87onmessage @ debuggerWorker.js:39
ExceptionsManager.js:61 Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `ZuotStockDetail`.

**Comment by hongyin163** [comment]
@leonardgithub do you update to 0.20.+ ?

**Comment by cnjon** [comment]
@leonardgithub Yes, #8 will be fix it.

**Comment by leonardgithub** [comment]
@hongyin163  RN 0.21 in both package.json and command line, and never changed.

**Comment by hongyin163** [comment]
@leonardgithub I haven't update to 0.21

**Comment by leonardgithub** [comment]
@hongyin163  @cnjon  I saw you fixed some problems these days, but the version is still 1.0.2, when will you release a new version? It seems no 1.0.3 now. Thanks.

**Comment by cnjon** [comment]
#9

**Comment by leonardgithub** [comment]
a question: what is the differences between the following? 

var {
    LineChart
}=require('../index.android');  // in sample/LineChart.js

var {
    LineChart
}=require('react-native-chart-android');

**Comment by hongyin163** [comment]
@leonardgithub In package.json file ,I set index.android.js as main file for this lib,so when you require('react-native-chart-android') ,it really require index.android.js

**Comment by leonardgithub** [comment]
@hongyin163  thanks. 
Another question: How to control the value's precision of the line chart? All my values are with two decimal places, but three places (the 3rd place show 0) when displayed in the coordinate, I just want to show two decimal places. I think it is because the range of the value: no problem if difference of the max value and the min value is large, while it is small it shows the extra 0 on the 3rd place.

**Comment by jainkjohnson** [comment]
@hongyin163 
question: How to hide the label in AxisBase. I used "drawLabels: false", but it's not working.

**Comment by hongyin163** [comment]
@jainkjohnson 
` private void setAxisInfo(AxisBase axis,ReadableMap v){
        if(v.hasKey("enable")) axis.setEnabled(v.getBoolean("enable"));
        if(v.hasKey("drawAxisLine")) axis.setDrawAxisLine(v.getBoolean("drawAxisLine"));

```
    if(v.hasKey("drawGridLines")) axis.setDrawGridLines(v.getBoolean("drawGridLines"));
    if(v.hasKey("drawLabels")) axis.setDrawLabels(v.getBoolean("drawLabels"));

    if(v.hasKey("textColor")) axis.setTextColor(Color.parseColor(v.getString("textColor")));
    if(v.hasKey("textSize")) axis.setTextSize((float)v.getDouble("textSize"));
    if(v.hasKey("gridColor")) axis.setGridColor(Color.parseColor(v.getString("gridColor")));

    if(v.hasKey("gridLineWidth")) axis.setGridLineWidth((float)v.getDouble("gridLineWidth"));
    if(v.hasKey("axisLineColor")) axis.setAxisLineColor(Color.parseColor(v.getString("axisLineColor")));
    if(v.hasKey("axisLineWidth")) axis.setAxisLineWidth((float)(v.getDouble("axisLineWidth")));
    if(v.hasKey("gridDashedLine")) {
        ReadableMap gdl=v.getMap("gridDashedLine");
        axis.enableGridDashedLine((float)gdl.getDouble("lineLength"),
                (float)gdl.getDouble("spaceLength"),
                (float)gdl.getDouble("phase"));
    }
    if (v.hasKey("xOffset")) {
        axis.setXOffset((float)(v.getDouble("xOffset")));
    }
    if (v.hasKey("yOffset")) {
        axis.setYOffset((float)(v.getDouble("yOffset")));
    }
}`
```

refer to PpAndroidChart lib，set it's property.

**Comment by jainkjohnson** [comment]
@hongyin163  Thanks for your response.
I have an another doubt regarding the values in the Yaxis. The graph render floating point number in the Yaxis but I want integer numbers. Is there any way to avoid floating numbers in Yaxis.
Thanks

**Comment by hongyin163** [comment]
@jainkjohnson sorry,i convert it to float
`
  //{XValues:[],YValues:[{Data:[],Label:""},{}]}
    @ReactProp(name="data")
    public void setData(LineChart chart,ReadableMap rm){

```
    ReadableArray xArray=rm.getArray("xValues");
    ArrayList<String> xVals=new ArrayList<String>();
    for(int m=0;m<xArray.size();m++){
        xVals.add(xArray.getString(m));
    }
    ReadableArray ra=rm.getArray("yValues");
    LineData chartData=new LineData(xVals);
    for(int i=0;i<ra.size();i++){
        ReadableMap map=ra.getMap(i);
        ReadableArray data=map.getArray("data");
        String label=map.getString("label");
        float[] vals=new float[data.size()];
        ArrayList<Entry> entries=new ArrayList<Entry>();
        for (int j=0;j<data.size();j++){
            vals[j]=(float)data.getDouble(j);
            Entry be=new Entry((float)data.getDouble(j),j);
            entries.add(be);
        }
        /*BarEntry be=new BarEntry(vals,i);
        entries.add(be);*/
        ReadableMap config= map.getMap("config");
        LineDataSet dataSet=new LineDataSet(entries,label);
        if(config.hasKey("drawCircles")) dataSet.setDrawCircles(config.getBoolean("drawCircles"));
        if(config.hasKey("circleSize")) dataSet.setCircleSize((float) config.getDouble("circleSize"));
        if(config.hasKey("lineWidth")) dataSet.setLineWidth((float) config.getDouble("lineWidth"));
        if(config.hasKey("drawValues")) dataSet.setDrawValues(config.getBoolean("drawValues"));
        if(config.hasKey("colors")){
            ReadableArray colorsArray = config.getArray("colors");
            ArrayList<Integer> colors = new ArrayList<>();
            for(int c = 0; c < colorsArray.size(); c++){
                colors.add(Color.parseColor(colorsArray.getString(c)));
            }
            dataSet.setColors(colors);
        }else if (config.hasKey("color")) {
            int[] colors=new int[]{Color.parseColor(config.getString("color"))};
            dataSet.setColors(colors);
        }
        if(config.hasKey("circleColors")){
            ReadableArray colorsArray = config.getArray("circleColors");
            ArrayList<Integer> colors = new ArrayList<>();
            for(int c = 0; c < colorsArray.size(); c++){
                colors.add(Color.parseColor(colorsArray.getString(c)));
            }
            dataSet.setCircleColors(colors);
        }else if (config.hasKey("circleColor")) {
            int[] colors=new int[]{Color.parseColor(config.getString("circleColor"))};
            dataSet.setCircleColors(colors);
        }
        if (config.hasKey("dashedLine")) {
            String[] dashedLine = config.getString("dashedLine").split(" ");
            dataSet.enableDashedLine(Integer.parseInt(dashedLine[0]), Integer.parseInt(dashedLine[1]), Integer.parseInt(dashedLine[2]));
        }
        chartData.addDataSet(dataSet);
    }
    //chart.setBackgroundColor(Color.WHITE);
    chart.setData(chartData);
    chart.invalidate();
}
```

}
`
you can change it in your project.

**Comment by jainkjohnson** [comment]
@hongyin163,
Which line should I edit to convert float to int?
