### ISSUE TITLE
after start，warning: 

### ISSUE THREAD

**Issue by YufJi** [hongyin163/react-native-chart-android#70]
Native component for' MPBarChart' doesnt exsit
Native component for' MPLineChart' doesnt exsit
...
...
...

**Comment by hongyin163** [comment]
@YufJi is there some debug info?

**Comment by YufJi** [comment]
不是bug 我不知道怎么用 是不是少装了文件图出不来.


发自网易邮箱大师
On 01/12/2017 20:37, hongyin163 wrote:

@YufJi is there some debug info?

**Comment by annshress** [comment]
same issue.

**Comment by DoraNemet** [comment]
I have the same problem. Any solution?

**Comment by hongyin163** [comment]
You can use android studio to find log info

**Comment by YufJi** [comment]
cause： native app needs MPchart dependenceLiabray
