### ISSUE TITLE
Wrong import

### ISSUE THREAD

**Issue by ianaz** [hongyin163/react-native-chart-android#72]
Hi,

the class MPCombinedChartManager is still importing the old ReactPropGroup class. I've tried to make a pull request but seem you disabled it...?
See https://github.com/facebook/react-native/commit/c1b7a369af7ca457819d682b15f47fae7e2732fc for more

**Comment by hongyin163** [comment]
no,you can change it ,and pull request

**Comment by ianaz** [comment]
Sorry was my fault. Done on #73

**Comment by hongyin163** [comment]
thanks!
