### ISSUE TITLE
Have any way to cancel the blank below the zero of Yaxis

### ISSUE THREAD

**Issue by RichardSleet** [hongyin163/react-native-chart-android#79]
![screenshot_20170515-094336](https://cloud.githubusercontent.com/assets/20389595/26039993/aa426826-3953-11e7-8971-503436e1610a.jpg)

**Comment by AlexDufresne** [comment]
￼
![screenshot_20170515-094336](https://cloud.githubusercontent.com/assets/20389595/26039984/89c19fd6-3953-11e7-91f0-da98dca30d00.jpg)

**Comment by hongyin163** [comment]
https://github.com/PhilJay/MPAndroidChart/wiki/YAxis

YAxis yAxis = mChart.getAxisLeft();
yAxis.setTypeface(...); // set a different font
yAxis.setTextSize(12f); // set the text size
yAxis.setAxisMinimum(0f); // start at zero
yAxis.setAxisMaximum(100f); // the axis maximum is 100
yAxis.setTextColor(Color.BLACK);
yAxis.setValueFormatter(new MyValueFormatter());
yAxis.setGranularity(1f); // interval 1
yAxis.setLabelCount(6, true); // force 6 labels
//... and more

**Comment by hongyin163** [comment]
start at zero

**Comment by hongyin163** [comment]
private  void setYAxisInfo(YAxis axis,ReadableMap v){
        if(v.hasKey("startAtZero")) axis.setStartAtZero(v.getBoolean("startAtZero"));
        if(v.hasKey("axisMaxValue")) axis.setAxisMaxValue((float) v.getDouble("axisMaxValue"));
